title: Dai Lingrui's Homepage
page-top-title: Dai Lingrui
top-section-bg-text: Be what you wanna be
home-subtitle: Dai Lingrui&ensp;|&ensp;代灵睿
copyright-text: '&copy; Dai Lingrui 2023-2025. All Rights Reserved.'
